-- Product Tables Migration for Render Database
-- This script creates the Products and ProductImages tables

-- Create Products table
CREATE TABLE IF NOT EXISTS "Products" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "TitleArabic" character varying(200),
    "SKU" character varying(20),
    "Description" text,
    "DescriptionArabic" text,
    "ProductType" character varying(50) NOT NULL DEFAULT 'Book',
    "AuthorId" integer,
    "PublisherId" integer,
    "CategoryId" integer,
    "Grade" character varying(50),
    "Subject" character varying(50),
    "PublicationDate" timestamp with time zone,
    "Pages" integer,
    "Language" character varying(20) NOT NULL DEFAULT 'Arabic',
    "Price" numeric(10,2),
    "OriginalPrice" numeric(10,2),
    "StockQuantity" integer NOT NULL DEFAULT 0,
    "CoverImageUrl" character varying(500),
    "IsAvailable" boolean NOT NULL DEFAULT true,
    "IsFeatured" boolean NOT NULL DEFAULT false,
    "IsNewRelease" boolean NOT NULL DEFAULT false,
    "Rating" numeric(3,2) NOT NULL DEFAULT 0.0,
    "RatingCount" integer NOT NULL DEFAULT 0,
    "ViewCount" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

-- Create ProductImages table
CREATE TABLE IF NOT EXISTS "ProductImages" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProductId" integer NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "ImageType" character varying(50) NOT NULL DEFAULT 'Gallery',
    "DisplayOrder" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_ProductImages" PRIMARY KEY ("Id")
);

-- Add foreign key constraints
ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Authors_AuthorId" 
    FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE SET NULL;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Categories_CategoryId" 
    FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE SET NULL;

ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Publishers_PublisherId" 
    FOREIGN KEY ("PublisherId") REFERENCES "Publishers" ("Id") ON DELETE SET NULL;

ALTER TABLE "ProductImages" ADD CONSTRAINT "FK_ProductImages_Products_ProductId" 
    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE;

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS "IX_Products_SKU" ON "Products" ("SKU");
CREATE INDEX IF NOT EXISTS "IX_Products_ProductType" ON "Products" ("ProductType");
CREATE INDEX IF NOT EXISTS "IX_Products_CategoryId" ON "Products" ("CategoryId");
CREATE INDEX IF NOT EXISTS "IX_Products_AuthorId" ON "Products" ("AuthorId");
CREATE INDEX IF NOT EXISTS "IX_Products_PublisherId" ON "Products" ("PublisherId");
CREATE INDEX IF NOT EXISTS "IX_Products_IsAvailable" ON "Products" ("IsAvailable");
CREATE INDEX IF NOT EXISTS "IX_Products_IsFeatured" ON "Products" ("IsFeatured");
CREATE INDEX IF NOT EXISTS "IX_Products_IsNewRelease" ON "Products" ("IsNewRelease");

CREATE INDEX IF NOT EXISTS "IX_ProductImages_ProductId" ON "ProductImages" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_ProductImages_DisplayOrder" ON "ProductImages" ("DisplayOrder");

-- Insert migration record
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") 
VALUES ('20250830125243_AddProductTables', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

-- Success message
SELECT 'Product tables created successfully!' as status;
